### ISSUE TITLE
Service not getting when trying to move this code to another project

### ISSUE THREAD

**Issue by anmol317** [darvincisec/DetectMagiskHide#1]
I am struggling with this one from a couple of days now. I downloaded this project and it was working file till i tried to move it to another project. 

The native-lib.c file was not able to resolve memset & strstr (including #include <string.h> in the .c file does the trick here.)

But till now i am not able to run this service in my project it simple just don't get initialized like it was doing in this particular project.

**Comment by darvincisec** [comment]
I dont have much info here.. Can you check if the service is marked as isolatedprocess in manifest file ?

**Comment by barkatthemoon18** [comment]
Greetings. 

I'm facing an issue which might be similar as OP comments. First off I cloned your code (Great work btw) and everything runs perfect. But when I change it to fulfill my requirements, by following the same logic as your code, it fails after getting the service bound. 

<img width="775" alt="imagen" src="https://user-images.githubusercontent.com/71537782/93658113-2591ff80-fa0f-11ea-86f9-5b6628c51101.png">

The exception as the images shows is DeadObjectException which implies that something crashed in the activity, and yet there's nothing wrong with it (Just a button which works fine). 
Am I missing something else? AIDL? Maybe the native library? 

Thanks in advance. 

Edit: As a matter of fact, the AIDL (in that test run) is exactly as yours, same as the service implementation.

**Comment by darvincisec** [comment]
Can you override onDestroy and onUnbind in IsolatedService and print logs there ? To rule out further, you can comment the native code invocation. 
Can you mention what exactly is the change you made?

**Comment by barkatthemoon18** [comment]
It wasn't strictly related to AIDL or the Isolated Process but the method naming in NDK. 

Fixed the method's name and now it's working. Thanks for you reply and help! Like I said, great work!

**Comment by darvincisec** [comment]
Thank you @fnazal18 
@anmol317 are you facing the issue still ?
