### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by charbelmkh** [darvincisec/DetectMagiskHide#4]
Hello @darvincisec ,

I tried to test the sample code on Android 11 , it does not work when magisk Hide is used.
I know it is not tested on Android 11 as bel the your blog (https://darvincitech.wordpress.com/2019/11/04/detecting-magisk-hide/)
but is there any way to make it work on Android 11?

Thanks,
Charbel

**Comment by darvincisec** [comment]
@charbelmkh , Is it tested with the latest code ? If there are logs, can you share? 
Also lwhat exactly is the toast msg you get?

**Comment by charbelmkh** [comment]
Hello @darvincisec,
Yes I'm using the latest code,
it seems to be working when compile with api level 29 but when I changed to api level 30 with hide it does't seems to be working.
I have a pixel phone rooted with android 11
and the toast message that I'm getting is "Magisk Not Found" (again this is when I compile with api level 30 and hide root ).

[magisk.log](https://github.com/darvincisec/DetectMagiskHide/files/5996670/magisk.log)

**Comment by darvincisec** [comment]
I compiled with api level 30, added more logs and generated an apk. Can you check with the apk pushed into the repo ? What version of Magisk are you using?

**Comment by charbelmkh** [comment]
The uploaded APK is release (can't find any logs),
I have updated the code and build it. same behaviour as before.
below are some logs (with and without hide).
[WITH_HIDE.log](https://github.com/darvincisec/DetectMagiskHide/files/6001552/WITH_HIDE.log)
[WIHTOUT_HIDE.log](https://github.com/darvincisec/DetectMagiskHide/files/6001554/WIHTOUT_HIDE.log)
![image](https://user-images.githubusercontent.com/19948770/108333246-cb75b000-71e1-11eb-9f77-3d611356ad2e.png)

**Comment by yogiou** [comment]
Seems only not working if set the targetSdkVersion to 30, not related to the compileSdkVersion.

**Comment by charbelmkh** [comment]
I just tried it, yes it seems when changing the targetSdkVersion to 30.
it's a bit weird thought.

**Comment by yogiou** [comment]
Maybe means that it is Android 11's behavior as it will run the compatibility mode in Android 11 if not specifying the targetSdkVersion to 30.

**Comment by barkatthemoon18** [comment]
It's a little bit late, but for Android 11 cases the Magisk Hide detection through mounts aren't present over /sbin folder. Maybe that's the reason why it can't be detected. Instead, by reading /proc/.../mounts, you should aim to look for any trace of magisk instead of looking specific paths. 
When no Magisk Hide is enabled, the symlink su binary is present on /system/bin, but its default place is on /dev folder which host another folder inside with a random name and fully root access (it isn't allowed to access, neither adb shell can reach).

**Comment by darvincisec** [comment]
The points are taken into account, I see it can detect magisk on Android 11.  I am closing this issue for now

**Comment by darvincisec** [comment]
Fixed it in the latest [changeset ](https://github.com/darvincisec/DetectMagiskHide/commit/30905a0c88909ef2da587a59e626af8407abc980)
